version: "3.8"
services:
  vite-docker: 
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports: 
      - 3000:3000
    working_dir: /app
    volumes: 
      - type: bind
        source: ./
        target: /app
    tty: true 